'use strict';

/**
 * Invoice display configuration — the authoritative definition of the blob
 * stored in company_settings.invoice_config (migration 095).
 *
 * This lives in its own module rather than in settings.controller.js because
 * three unrelated layers need it and none of them should depend on a
 * controller:
 *   - settings.controller.js  — validates it on write, returns it on read
 *   - templates/invoiceThemes — reads it at render time
 *   - customer_invoices.controller.js — resolves it for PDF + public views
 *
 * ── The empty-config contract ────────────────────────────────────────────────
 * DEFAULT_INVOICE_CONFIG must reproduce EXACTLY the behaviour the templates
 * had before any of this existed. Every stored blob is deep-merged over these
 * defaults at read time, so `{}` (the column default for every pre-existing
 * row) renders historical invoices byte-identically. Any new toggle added
 * later must default to "off"/"as it was" for the same reason — the defaults
 * here are a backwards-compatibility guarantee, not a taste preference.
 */

const { z } = require('zod');

// Themes a shared/public invoice view may be forced into. Kept in sync with
// templates/invoiceThemes/registry.js.
const VALID_INVOICE_THEMES = [
  'simple', 'modern', 'luxury', 'stylish',
  'advanced_gst', 'advanced_gst_tally', 'billbook',
  'advanced_gst_a5', 'billbook_a5',
];

// Industry presets only pre-fill the toggles below when chosen in the UI —
// they are stored for display but carry no rendering behaviour of their own,
// so an unrecognised value is harmless.
const INDUSTRY_TYPES = ['automobile', 'retail', 'pharma', 'manufacturing', 'services', 'other'];

const DEFAULT_INVOICE_CONFIG = {
  industry_type: 'automobile',

  flags: {
    // Outstanding balance for this customer, printed in the totals block.
    show_party_balance: false,
    // Render zero-charge lines as "FREE" instead of ₹0.00. Display-only —
    // see isFreeLine() in templates/invoiceThemes/shared.js for why this
    // never recomputes totals.
    free_item_qty: false,
    // Optional detail line under each item name (customer_invoice_items.item_description).
    show_item_description: false,
    // Company phone in the invoice header. Defaults ON because every theme
    // already printed it before this config existed.
    show_phone: true,
    // Append time-of-day to the invoice date.
    show_time: false,
    // Prior prices this customer paid for the same item.
    price_history: false,
    // Theme key forced on the public /by-token view regardless of the theme
    // selected for print. null = use the normal invoice_theme.
    auto_share_theme: null,
  },

  // Optional header fields. vehicle_number defaults ON because it already
  // appeared on every theme (Spinoto is a workshop — it's the norm, not an
  // extra). po_number / eway_bill are genuinely new, so they default off.
  header_fields: {
    po_number: false,
    eway_bill: false,
    vehicle_number: true,
  },

  // Item table columns. price/qty default ON — they were always rendered.
  // The remaining three are new columns with no historical data.
  //
  // Note: '#', item name, HSN/SAC, discount, GST and amount are NOT
  // toggleable. They're either structural (you cannot have an item table
  // with no item name) or legally required on a GST tax invoice.
  item_columns: {
    price: true,
    qty: true,
    batch_no: false,
    exp_date: false,
    mfg_date: false,
  },

  // User-defined extras. Definitions only — values live per-invoice, keyed by
  // these ids (customer_invoices.custom_fields / customer_invoice_items.custom_values).
  custom_fields: [],   // [{ id, label, enabled }] — extra invoice header rows
  custom_columns: [],  // [{ id, label, enabled }] — extra item table columns
};

const MAX_CUSTOM = 10;

// Ids are generated by the frontend and must be stable forever, so they're
// validated for shape but never regenerated server-side. Restricting the
// charset also means they're safe to use as object keys and in HTML.
const customEntrySchema = z.object({
  id:      z.string().trim().regex(/^[a-zA-Z0-9_-]{1,40}$/, 'Invalid custom field id'),
  label:   z.string().trim().min(1).max(40),
  enabled: z.boolean().default(true),
});

// .partial() throughout: the frontend may send only the keys it changed, and
// resolveInvoiceConfig() fills in the rest. .strict() is deliberately NOT
// used — unknown keys are stripped by Zod's default behaviour, which is what
// we want for forward compatibility with a newer frontend.
const invoiceConfigSchema = z.object({
  industry_type: z.enum(INDUSTRY_TYPES).optional(),
  flags: z.object({
    show_party_balance:    z.boolean(),
    free_item_qty:         z.boolean(),
    show_item_description: z.boolean(),
    show_phone:            z.boolean(),
    show_time:             z.boolean(),
    price_history:         z.boolean(),
    auto_share_theme:      z.enum(VALID_INVOICE_THEMES).nullable(),
  }).partial().optional(),
  header_fields: z.object({
    po_number:      z.boolean(),
    eway_bill:      z.boolean(),
    vehicle_number: z.boolean(),
  }).partial().optional(),
  item_columns: z.object({
    price:    z.boolean(),
    qty:      z.boolean(),
    batch_no: z.boolean(),
    exp_date: z.boolean(),
    mfg_date: z.boolean(),
  }).partial().optional(),
  custom_fields:  z.array(customEntrySchema).max(MAX_CUSTOM).optional(),
  custom_columns: z.array(customEntrySchema).max(MAX_CUSTOM).optional(),
}).optional();

/**
 * Deep-merge a stored (possibly empty, possibly partial, possibly null) config
 * over the defaults, so every consumer gets a fully-populated object and no
 * template ever has to null-check a flag.
 *
 * Only the four known nested objects are merged key-by-key; the two arrays are
 * replaced wholesale, since a user removing a custom field must actually
 * remove it rather than have the old one merged back in.
 */
function resolveInvoiceConfig(raw) {
  const src = (raw && typeof raw === 'object' && !Array.isArray(raw)) ? raw : {};
  const d = DEFAULT_INVOICE_CONFIG;

  const mergeSection = (key) => ({
    ...d[key],
    ...(src[key] && typeof src[key] === 'object' && !Array.isArray(src[key]) ? src[key] : {}),
  });

  const cleanList = (key) => {
    const list = Array.isArray(src[key]) ? src[key] : d[key];
    return list
      .filter(e => e && typeof e === 'object' && typeof e.id === 'string' && typeof e.label === 'string')
      .slice(0, MAX_CUSTOM)
      .map(e => ({ id: e.id, label: e.label, enabled: e.enabled !== false }));
  };

  return {
    industry_type: INDUSTRY_TYPES.includes(src.industry_type) ? src.industry_type : d.industry_type,
    flags:         mergeSection('flags'),
    header_fields: mergeSection('header_fields'),
    item_columns:  mergeSection('item_columns'),
    custom_fields:  cleanList('custom_fields'),
    custom_columns: cleanList('custom_columns'),
  };
}

module.exports = {
  VALID_INVOICE_THEMES,
  INDUSTRY_TYPES,
  DEFAULT_INVOICE_CONFIG,
  invoiceConfigSchema,
  resolveInvoiceConfig,
  MAX_CUSTOM,
};
